force-app/main/default/objects/CleanToDoList__mdt/CleanToDoList__mdt.object-meta.xml
<CustomObject>
    <description>For Clean to do when create dade &gt; 3 months</description>
    <label>CleanToDoList</label>
    <pluralLabel>CleanToDoLists</pluralLabel>
</CustomObject>

objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <defaultValue>$RecordType.Name</defaultValue>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>Creation_Date__c</fullName>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Creation Date</label>
    <type>Date</type>
</CustomField>

objects/ToDo__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>ExternalId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/ToDo__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

classes/CleanOldTodo.cls
public with sharing class CleanOldTodo implements Database.Batchable<ToDo__c>, Database.AllowsCallouts {
    public List<ToDo__c> start(Database.BatchableContext param1) {      
        Integer daysAgo = Integer.valueOf([SELECT Days__c FROM CleanToDoList__mdt][0].Days__c);
        
        return [SELECT Id, 
                Name,
                Description__c,
                Creation_Date__c,
                Category__c,
                Priority__c,
                Status__c,
                ExternalId__c,
                RecordTypeId,
                CreatedDate FROM ToDo__c WHERE CreatedDate < :Date.today().addDays(-daysAgo)];
    }
    public void execute(Database.BatchableContext param1, List<ToDo__c> oldTodos) {
        TodoBatchHelper.pushDeleted(oldTodos);
        delete oldTodos;
    }

    public void finish(Database.BatchableContext param1) {
    }
}