force-app/main/default/objects/Sub_ToDo__c/Sub_ToDo__c.object-meta.xml
<CustomObject>
    <label>Sub ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub ToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_ToDo__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <label>External Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sub_ToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>Sub ToDos</relationshipLabel>
    <relationshipName>Sub_ToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ToDo__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>ExternalId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ResponseWrapperSub.cls
public with sharing class ResponseWrapperSub {

    public String id { get; set; }
    public String name { get; set; }
    public String status { get; set; }
    public String relatedTodo { get; set; }
    public String relatedExternal { get; set; }
    public String externalId { get; set; }

    public static ResponseWrapperSub doMapping(Sub_ToDo__c sub) {
        ResponseWrapperSub wrapper = new ResponseWrapperSub();
        wrapper.id = sub.Id;
        wrapper.name = sub.Name;
        wrapper.status = sub.Status__c;
        wrapper.relatedTodo = sub.ToDo__c;
        for(ToDo__c todo : [SELECT Id, ExternalId__c FROM ToDo__c]) {
            if(todo.Id == wrapper.relatedTodo) {
                wrapper.relatedExternal = todo.ExternalId__c;
            }
        }
        // wrapper.relatedExternal = sub.ToDo__r.ExternalId__c;
        wrapper.externalId = sub.External_Id__c;
        return wrapper;
    }

    public static List<ResponseWrapperSub> doMappingToWrappers(List<Sub_ToDo__c> subs){
        List<ResponseWrapperSub> wrappers = new List<ResponseWrapperSub>();

        for (Sub_ToDo__c sub: subs) {
            ResponseWrapperSub wrapper = doMapping(sub);
            wrappers.add(wrapper);
        }

        return wrappers;
    }
}