objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <defaultValue>$RecordType.Name</defaultValue>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/classes/ToDoControllerTest.cls
@isTest
private class ToDoControllerTest {
    @TestSetup
    static void setup() {
        ToDo__c todo = new ToDo__c(
                Name = 'Test01',
                Description__c = 'Description',
                Category__c = 'Today',
                Status__c = 'Ready to take'
        );

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('TodoResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new TodoHttpCalloutMock());

        insert todo;
    }

    @IsTest
    static void testgetToDos() {
        ToDo__c todo = [SELECT Id FROM ToDo__c WHERE Name = 'Test01'];

        Test.startTest();
        List<ToDo__c> todos = ToDoController.getToDos();
        Test.stopTest();

        System.assert(todos != null);
        for (ToDo__c result: todos){
            System.assertEquals(toDo.Id, result.Id);

        }
    }
    @IsTest
    static void testgetTodayId() {
        Test.startTest();
        Id todoId = ToDoController.getTodayId();
        Test.stopTest();
        System.assert(todoId != null);
     	System.assertEquals(todoId, '00G5j0000010so8EAA');
    }
    @IsTest
    static void testgetTomorrowId() {
        Test.startTest();
        Id todoId = ToDoController.getTomorrowId();
        Test.stopTest();
        System.assert(todoId != null);
     	System.assertEquals(todoId, '00G5j0000010so9EAA');
    }
    @IsTest
    static void testgetLaterId() {
        Test.startTest();
        Id todoId = ToDoController.getLaterId();
        Test.stopTest();
        System.assert(todoId != null);
     	System.assertEquals(todoId, '00G5j0000010so7EAA');
    }
}