objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ToDo__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EMailToCaseTriggerHandlerHelper.cls
public with sharing class EMailToCaseTriggerHandlerHelper {
    public static void createCaseTodo(List<Case> cases) {
        List<ToDo__c> todos = new List<ToDo__c>();

        for (Case cs : cases) {
            if (cs.Origin == 'Email') {
                ToDo__c todo = new ToDo__c(
                    Name = cs.Subject,
                    Priority__c = 'Low',
                    Description__c = (cs.Description).abbreviate(50)
                );
                todos.add(todo);
                System.debug(todo);
            }
        }
        
        insert todos;
    }
}