objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ToDo__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>ExternalId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TodoBatchHelperTest.cls
@IsTest
private class TodoBatchHelperTest {
    public static ToDo__c todo = new ToDo__c(
        Id = 'a0009000007RU4WAAW',
        Name = 'Test01',
        ExternalId__c = 'a010900000nVG0NAAW',
        RecordTypeId = '012090000006M9QAAU',
        Status__c = 'Ready to take'
    );
    
    @IsTest
    static void testPushInserted() {
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('TodoResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);
        List<ToDo__c> todos = new List<ToDo__c>();
        todos.add(todo);
        Test.startTest();
        TodoBatchHelper.pushInserted(todos);
        Test.stopTest();
        System.assertEquals(1, todos.size());
    }

    @IsTest
    static void testpushUpdated() {
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('TodoResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new TodoHttpCalloutMock());
        List<ToDo__c> todos = new List<ToDo__c>();
        todos.add(todo);
        Test.startTest();
        TodoBatchHelper.pushUpdated(todos);
        Test.stopTest();
        System.assertEquals(1, todos.size());
    }

    @IsTest
    static void testpushDeleted() {
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('TodoResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new TodoHttpCalloutMock());
        List<ToDo__c> todos = new List<ToDo__c>();
        todos.add(todo);
        Test.startTest();
        TodoBatchHelper.pushDeleted(todos);
        Test.stopTest();
        System.assertEquals(1, todos.size());
    }
}